### PR TITLE
Feat : Added Copyright year section in footer 

### LINKED ISSUE #26: feat : Add a copyright section in footer
Copyright section is missing currently in our footer 
@Akshat111111 assign this to me I will add it and that will not be direct copy paste of text , It will fetch the current year dynamically .

### PR DESCRIPTION
**Pull request by Meetjain1**
Closes #26 

brief description for the PR:

### PR Description

**Feature Added:** Copyright Year Section

**Details:**
- Added a copyright year section to the footer using HTML, CSS, and JavaScript.
- The JavaScript code dynamically fetches and displays the current year to ensure the copyright information is always up-to-date.
- CSS was applied to position and style the copyright text appropriately at the bottom of the footer.

**Benefits:**
- Ensures the copyright year is always current without needing manual updates.
- Enhances the footer with clear and professional copyright information.

new easy

VSOC email - meetofficialhere@gmail.com

### CODE REVIEW

**Comment by Meetjain1** [comment]
@Akshat111111 have a look on this pr . Thanks

**Comment by Meetjain1** [comment]
@Akshat111111 have a look on this pr . Thanks

**Comment by Meetjain1** [comment]
@Akshat111111 please review this pr before the deadline . Thanks

**Comment by Meetjain1** [comment]
@Akshat111111 please review this pr before the deadline . Thanks

**Comment by Meetjain1** [comment]
@Akshat111111 check this pr also . Thanks

**Review by Akshat111111 — COMMENTED** [review]
yeah, it works

**Comment by Meetjain1** [comment]
@Akshat111111 please add points also . Thanks

**Comment by Akshat111111** [comment]
yeah, i will send the list to the organizers soon

**Pull request merged**
