### PR TITLE
Make buttons responsive

### PR DESCRIPTION
**Pull request by kratik1237**
Closed issue #3 
Had made the buttons of the file responsive .

https://github.com/Akshat111111/new-and-easy-Travel/assets/142149999/e31ee5db-56fa-4e5e-acbc-ab379591dff3

### CODE REVIEW

**Comment by kratik1237** [comment]
@Akshat111111 please check the pr #3

**Review by Akshat111111 — COMMENTED** [review]
Also mention their name which are now responsive, then i will merge

**Comment by kratik1237** [comment]
all website buttons and images @Akshat111111

**Comment by kratik1237** [comment]
Can you give points? @Akshat111111

**Pull request merged**
